### ISSUE TITLE
[Suggestion] Rename folder and addon name

### ISSUE THREAD

**Issue by MuTLY** [Witnesscm/TinyInspect#1]
Rename the folder and the addon name to "TinyInspect-Continued" and then refer to this new folder name in files, so it's distinct from other addons based on it, e.g. "TinyInspect-Reforged".

**Comment by Witnesscm** [comment]
Thanks for your suggestion, but I've only made a few minor changes to make it support 10.2.7 patch, so I currently have no plans to rename and publish it to CurseForge.

As explained in README, user can temporarily use WowUp's 'Install from URL' feature to install.
