### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by nanjuekaien1** [Witnesscm/TinyInspect#4]
..terface/AddOns/InspectEquip/Src/Modules/Tooltips.lua:393: bad argument #1 to 'gmatch' (string expected, got table)
Count: 99

Call Stack:
[string "=[C]"]: ?
[string "=[C]"]: in function `gmatch'
[string "@Interface/AddOns/InspectEquip/Src/Modules/Tooltips.lua"]:393: in function <...terface/AddOns/InspectEquip/Src/Modules/Tooltips.lua:384>
[string "@Interface/AddOns/InspectEquip/Src/Modules/Tooltips.lua"]:414: in function `AddToTooltip'
[string "@Interface/AddOns/InspectEquip/Src/Modules/Tooltips.lua"]:426: in function `ParseItem'
[string "@Interface/AddOns/InspectEquip/Src/Modules/Tooltips.lua"]:440: in function <...terface/AddOns/InspectEquip/Src/Modules/Tooltips.lua:436>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
...
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/TinyInspect/libs/LibItemInfo.lua"]:115: in function AddOns/TinyInspect/libs/LibItemInfo.lua:104>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/TinyInspect/ItemLevel.lua"]:146: in function
[string "@Interface/AddOns/TinyInspect/ItemLevel.lua"]:211: in function AddOns/TinyInspect/ItemLevel.lua:176>
[string "=[C]"]: in function `SetItemButtonQuality'
[string "@Interface/AddOns/Blizzard_EncounterJournal/Mainline/Blizzard_EncounterJournal.lua"]:204: in function `Init'
[string "@Interface/AddOns/Blizzard_EncounterJournal/Mainline/Blizzard_EncounterJournal.lua"]:2139: in function `EncounterJournal_LootCallback'
[string "@Interface/AddOns/Blizzard_EncounterJournal/Mainline/Blizzard_EncounterJournal.lua"]:888: in function <...ounterJournal/Mainline/Blizzard_EncounterJournal.lua:884>

**Comment by nanjuekaien1** [comment]
单独开InspectEquip 不报错，同时开启了TinyInspect和InspectEquip 第一次上线就出现上面报错，找InspectEquip说过，说不是他问题。

**Comment by Witnesscm** [comment]
下了个InspectEquip没发现有报错

**Comment by nanjuekaien1** [comment]
https://nga.178.com/read.php?tid=8749947&fav=:F8897E1E1
我下的是这个

**Comment by nanjuekaien1** [comment]
InspectEquip我删了，看BagSync的提示大版本出处吧，
