### ISSUE TITLE
Text on item icons in warband bank?

### ISSUE THREAD

**Issue by drnoonien** [Witnesscm/TinyInspect#5]
Hey, is there a possibility for you to extend the addon to include all the item-icon texts that we have in the bag/bank to also show up in the warband bank?

I know you're only keeping the addon alive, but figured I'd ask.

Referring to these texts

![](https://i.imgur.com/YBxReSe.png)

**Comment by Witnesscm** [comment]
Sure, show item ilvl on most frames in game is one of the features of this addon. I will add this feature later today.
